# Generated by Django 2.2 on 2020-05-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(max_length=255),
        ),
    ]
